P10C For the section "Correlations between independent variables." There is AttributeError: module 'pandas' has no attribute 'scatter_matrix'
Thus,
Import an package "from pandas.plotting import scatter_matrix"

Modify the "axs = pd.scatter_matrix(numeric_data, figsize=(8, 8));" to "axs = scatter_matrix(numeric_data, figsize=(8, 8));"